language: R
cache: packages
R: bioc-release
dist: trusty
latex: false
os:
  - linux
  
env:
  - R_BIOC_VERSION: "3.9"

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - R -e 'rmarkdown::render("./index.Rmd")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "."