language: R
cache: packages
R: bioc-devel
dist: trusty
latex: false
os:
  - linux

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'BiocManager::install(version = "3.10", ask = FALSE)'
  - Rscript -e 'BiocManager::install("scMerge", version = "3.10", ask = FALSE)'
  - R -e 'rmarkdown::render("./index.Rmd")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "."