language: R
cache: packages
R: bioc-devel
dist: trusty
latex: false
os:
  - linux

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'BiocManager::install(version = "3.10", ask = FALSE)'
  - Rscript -e 'BiocManager::install(c(
    "scMerge", "devtools",
    "DropletUtils", "edgeR",
    "ggpubr", "MAST", 
    "mclust", "monocle", 
    "plyr", "Rtsne", 
    "scales", "scater", 
    "scran", "tidyverse", "viridis",
    "DescTools", "amap", "doParallel", "ggridges", "lme4", "mice", "methods", "caret", "randomForest", "clusteval", "dendextend", "gmodels", "e1071"
    ), version = "3.10", ask = FALSE)'
  - Rscript -e 'install.packages("https://github.com/kevinwang09/SingleCellPlus/raw/master/scdney_mac_binary/scdney_0.1.3.tgz", repos = NULL)'
  - R -e 'rmarkdown::render_site(".")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "."