language: R
R: bioc-devel
dist: xenial
latex: false

env:
  - R_BIOC_VERSION: "3.10"

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e 'BiocManager::version()'
  - Rscript -e 'BiocManager::install(c(
  "DropletUtils", "edgeR",
	"ggpubr", "MAST", 
	"plyr", "Rtsne", 
	"scales", "scater", 
	"scran", "tidyverse", 
	"viridis", "monocle",
	"kevinwang09/scdney"), version = "3.10", ask = FALSE)'
  - Rscript -e 'BiocManager::version()'
  - R -e 'rmarkdown::render_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "."