---
title: "Liver Datasets"
author: "Yingxin Lin"
date: "21/05/2019"
output: html_document
---


```{r}
library(SingleCellExperiment)
library(scater)
library(scran)
```



# Su et al. data

## Raw data

```{r}
exprsMat <- read.csv("/Users/yingxinlin/Dropbox (Sydney Uni)/Single Cell Reserach (1)/WorkshopSC-2018/data/GSE87795_counts.csv", row.names = 1)
dim(exprsMat)
stage <- unlist(lapply(strsplit(colnames(exprsMat), "_"), "[[", 1))
table(stage)

dim(exprsMat)
```



## Processed data

### GSE87795 Su et al.

```{r}

sce_GSE87795 <- readRDS("sce_GSE87795.rds")
sce_GSE87795
scater::plotPCA(sce_GSE87795, colour_by = "cellTypes")
scater::plotPCA(sce_GSE87795, colour_by = "stage")
```

### GSE90047

```{r}
sce_GSE90047 <- readRDS("sce_GSE90047.rds")

scater::plotPCA(sce_GSE90047, colour_by = "cellTypes")
scater::plotPCA(sce_GSE90047, colour_by = "stage")
```


### GSE87038 

```{r}
sce_GSE87038 <- readRDS("sce_GSE87038.rds")
scater::plotPCA(sce_GSE87038, colour_by = "cellTypes")
scater::plotPCA(sce_GSE87038, colour_by = "stage")
```


### sce_GSE96981 

```{r}
sce_GSE96981 <- readRDS("sce_GSE96981.rds")
scater::plotPCA(sce_GSE96981, colour_by = "cellTypes")
scater::plotPCA(sce_GSE96981, colour_by = "stage")
```




<!-- ```{r} -->
<!-- sce_combine<-scMerge(sce_combine, ctl = which(rownames(sce_combine)%in%segList$mouse$mouse_scSEG), -->
<!--                      kmeansK = c(6,2,3,3), -->
<!--                      exprs = "logcounts", -->
<!--                      hvg_exprs="counts", -->
<!--                      marker=NULL, -->
<!--                      ruvK = 20, -->
<!--                      cell_type = NULL, -->
<!--                      fast_svd = FALSE, -->
<!--                      dist = "cor", -->
<!--                      replicate_prop = 0.5, -->
<!--                      WV = sce_combine$stage, -->
<!--                      WV_marker = c("Afp","Alb","Epcam"), -->
<!--                      return_all_RUV = FALSE, -->
<!--                      assay_name = "scMerge_scSEG") -->
<!-- ``` -->
